all:
	pdflatex parsifal-short.tex && bibtex parsifal-short.aux && pdflatex parsifal-short.tex && pdflatex parsifal-short.tex

clean:
	rm -f parsifal-short.aux parsifal-short.pdf parsifal-short.bbl parsifal-short.log parsifal-short.blg
