let rsa_private_key_a = [
  mkf "version"         AT_SmallInteger;
  mkf "modulus"         AT_Integer;
  mkf "publicExponent"  AT_Integer;
  mkf "privateExponent" AT_Integer;
  mkf "prime1"          AT_Integer;
  mkf "prime2"          AT_Integer;
  mkf "exponent1"       AT_Integer;
  mkf "exponent2"       AT_Integer;
  mkf "coefficient"     AT_Integer;
]

let rsa_public_key_a = [
  mkf "p_modulus"         AT_Integer;
  mkf "p_publicExponent"  AT_Integer;
]

let _ =
  handle_desc "rsa_private_key" rsa_private_key_a;;
  handle_desc "rsa_public_key" rsa_public_key_a;;

