all:
	pdflatex OlivierLevillain.tex && bibtex OlivierLevillain.aux && pdflatex OlivierLevillain.tex && pdflatex OlivierLevillain.tex

clean:
	rm -f OlivierLevillain.aux OlivierLevillain.pdf OlivierLevillain.bbl OlivierLevillain.log OlivierLevillain.blg
